# Task: classification
task:
  name: "classification"

# Dataset config
data:
  root: "/home/test/Desktop/python/EEG_data/AAD_dataset/AAD_DTU/Processed/Dataset"
  file: "S{subject}_Dataset_1s.npz"
  total_sub: 18
  num_channels: 64
  dataset_class: "EEGDatasetDTU"
  split_method: "random"  # 划分策略类型
  split_params:                 # 策略相关参数
    train_ratio: 0.8           # 通用参数
  
# Model
model:
  class_name: "EEGNet"

# Training config
training:
  batch_size: 60
  epochs: 100
  optimizer: "adamw"
  optimizer_params:
    lr: 0.001
    weight_decay: 0.001
  scheduler: "plateau"
  scheduler_params:
    mode: "min"
    factor: 0.9
    patience: 1
  
# Model env & save
environment:
  device: "auto"
  save_dir: "./results"
  
# Logs
logging:
  save_dir: "./logs"
  format: "json"  # 可选：json/txt/csv
  filename_template: "{model}+{dataset}+{split}+{timestamp}"
  monitor_metrics: "val_acc"